homepage: "https://github.com/Lowlaw4/aRepo1"
language: c  # or jvm
primary_contact: "maintainer@example.com"

# Fuzzing configuration
fuzzing_engines:
  - libfuzzer
  
sanitizers:
  - address      # detects memory corruption
  - undefined    # detects undefined behavior
  - memory       # detects uninitialized reads
